/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  CalendarConfig: () => import('#controllers/calendar_config_controller'),
  Health: () => import('#controllers/health_controller'),
  Load: () => import('#controllers/load_controller'),
  OrderPlanning: () => import('#controllers/order_planning_controller'),
  Perf: () => import('#controllers/perf_controller'),
  Pipeline: () => import('#controllers/pipeline_controller'),
  PlanningBoard: () => import('#controllers/planning_board_controller'),
  Scheduler: () => import('#controllers/scheduler_controller'),
  StaticSync: () => import('#controllers/static_sync_controller'),
  SuggestionFirm: () => import('#controllers/suggestion_firm_controller'),
  Suivi: () => import('#controllers/suivi_controller'),
  X3Data: () => import('#controllers/x3_data_controller'),
  X3Writeback: () => import('#controllers/x3_writeback_controller'),
}
