/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  CalendarConfig: () => import('#controllers/calendar_config_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  DashboardLayout: () => import('#controllers/dashboard_layout_controller'),
  Health: () => import('#controllers/health_controller'),
  Load: () => import('#controllers/load_controller'),
  OrderPlanning: () => import('#controllers/order_planning_controller'),
  Perf: () => import('#controllers/perf_controller'),
  PlanningBoard: () => import('#controllers/planning_board_controller'),
  PrintConfig: () => import('#controllers/print_config_controller'),
  Print: () => import('#controllers/print_controller'),
  PrintJournal: () => import('#controllers/print_journal_controller'),
  Scenario: () => import('#controllers/scenario_controller'),
  Scheduler: () => import('#controllers/scheduler_controller'),
  StaticSync: () => import('#controllers/static_sync_controller'),
  SuggestionFirm: () => import('#controllers/suggestion_firm_controller'),
  Suivi: () => import('#controllers/suivi_controller'),
  X3Data: () => import('#controllers/x3_data_controller'),
}
