/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CapacityClosureSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'dateFrom', 'dateTo', 'factor', 'id', 'motif', 'scope'] as const
  $columns = CapacityClosureSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dateFrom: string
  @column()
  declare dateTo: string
  @column()
  declare factor: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare motif: string
  @column()
  declare scope: string
}

export class CapacityHolidayOverrideSchema extends BaseModel {
  static $columns = ['active', 'date', 'id'] as const
  $columns = CapacityHolidayOverrideSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare date: string
  @column({ isPrimary: true })
  declare id: number
}

export class LocalMenuSchema extends BaseModel {
  static $columns = ['chapter', 'label', 'name', 'value'] as const
  $columns = LocalMenuSchema.$columns
  @column({ isPrimary: true })
  declare chapter: number
  @column()
  declare label: string
  @column()
  declare name: string
  @column()
  declare value: number
}

export class OfOverrideSchema extends BaseModel {
  static $columns = ['createdAt', 'dateDebut', 'dateFin', 'id', 'note', 'numOf', 'status', 'updatedAt', 'workstation'] as const
  $columns = OfOverrideSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dateDebut: string | null
  @column()
  declare dateFin: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare note: string | null
  @column()
  declare numOf: string
  @column()
  declare status: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workstation: string | null
}

export class OrderLineOverrideSchema extends BaseModel {
  static $columns = ['createdAt', 'dateLivraison', 'id', 'ligne', 'numCommande', 'updatedAt'] as const
  $columns = OrderLineOverrideSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dateLivraison: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ligne: string
  @column()
  declare numCommande: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ScenarioSchema extends BaseModel {
  static $columns = ['auteur', 'createdAt', 'dataAt', 'description', 'evaluatedAt', 'id', 'mutations', 'nom', 'statut', 'strategy', 'updatedAt'] as const
  $columns = ScenarioSchema.$columns
  @column()
  declare auteur: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dataAt: string | null
  @column()
  declare description: string | null
  @column()
  declare evaluatedAt: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mutations: string
  @column()
  declare nom: string
  @column()
  declare statut: string
  @column()
  declare strategy: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StaticArticleSchema extends BaseModel {
  static $columns = ['category', 'code', 'description', 'famille', 'reorderDelay', 'supplyType', 'syncedAt', 'typologie'] as const
  $columns = StaticArticleSchema.$columns
  @column()
  declare category: string
  @column({ isPrimary: true })
  declare code: string
  @column()
  declare description: string
  @column()
  declare famille: string
  @column()
  declare reorderDelay: number
  @column()
  declare supplyType: string
  @column()
  declare syncedAt: number
  @column()
  declare typologie: string
}

export class StaticGammeSchema extends BaseModel {
  static $columns = ['article', 'id', 'rate', 'syncedAt', 'workstation', 'workstationLabel'] as const
  $columns = StaticGammeSchema.$columns
  @column()
  declare article: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare rate: number
  @column()
  declare syncedAt: number
  @column()
  declare workstation: string
  @column()
  declare workstationLabel: string
}

export class StaticNomenclatureSchema extends BaseModel {
  static $columns = ['componentArticle', 'componentDescription', 'componentType', 'consumptionNature', 'id', 'level', 'linkQuantity', 'parentArticle', 'parentDescription', 'syncedAt'] as const
  $columns = StaticNomenclatureSchema.$columns
  @column()
  declare componentArticle: string
  @column()
  declare componentDescription: string
  @column()
  declare componentType: string
  @column()
  declare consumptionNature: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare level: number
  @column()
  declare linkQuantity: number
  @column()
  declare parentArticle: string
  @column()
  declare parentDescription: string
  @column()
  declare syncedAt: number
}

export class StaticWorkstationSchema extends BaseModel {
  static $columns = ['code', 'daycap0', 'daycap1', 'daycap2', 'daycap3', 'daycap4', 'daycap5', 'daycap6', 'description', 'eff', 'id', 'shr', 'stoloc', 'syncedAt', 'twd', 'usePct', 'wcr', 'wcrfcy', 'wstnbr', 'wsttyp'] as const
  $columns = StaticWorkstationSchema.$columns
  @column()
  declare code: string
  @column()
  declare daycap0: number
  @column()
  declare daycap1: number
  @column()
  declare daycap2: number
  @column()
  declare daycap3: number
  @column()
  declare daycap4: number
  @column()
  declare daycap5: number
  @column()
  declare daycap6: number
  @column()
  declare description: string
  @column()
  declare eff: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare shr: number
  @column()
  declare stoloc: string
  @column()
  declare syncedAt: number
  @column()
  declare twd: string
  @column()
  declare usePct: number
  @column()
  declare wcr: string
  @column()
  declare wcrfcy: string
  @column()
  declare wstnbr: number
  @column()
  declare wsttyp: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'lastEnv', 'lastLoginAt', 'updatedAt', 'username', 'x3PasswordEncrypted'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastEnv: string
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare username: string
  @column()
  declare x3PasswordEncrypted: string | null
}
