/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class LocalMenuSchema extends BaseModel {
  static $columns = ['chapter', 'label', 'name', 'value'] as const
  $columns = LocalMenuSchema.$columns
  @column({ isPrimary: true })
  declare chapter: number
  @column()
  declare label: string
  @column()
  declare name: string
  @column()
  declare value: number
}

export class OfOverrideSchema extends BaseModel {
  static $columns = ['createdAt', 'dateDebut', 'dateFin', 'id', 'note', 'numOf', 'status', 'updatedAt', 'workstation'] as const
  $columns = OfOverrideSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dateDebut: string | null
  @column()
  declare dateFin: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare note: string | null
  @column()
  declare numOf: string
  @column()
  declare status: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workstation: string | null
}
