/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ApproDecisionLedgerSchema extends BaseModel {
  static $columns = [
    'article',
    'causePredit',
    'cleLogique',
    'confiancePredit',
    'createdAt',
    'decidedAt',
    'echeance',
    'expiree',
    'fournisseur',
    'id',
    'lastSeenAt',
    'nature',
    'niveauPredit',
    'quantite',
    'statut',
    'verdictPredit',
  ] as const
  $columns = ApproDecisionLedgerSchema.$columns
  @column()
  declare article: string
  @column()
  declare causePredit: string | null
  @column()
  declare cleLogique: string
  @column()
  declare confiancePredit: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare decidedAt: DateTime
  @column.date()
  declare echeance: DateTime | null
  @column()
  declare expiree: boolean
  @column()
  declare fournisseur: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare lastSeenAt: DateTime | null
  @column()
  declare nature: string
  @column()
  declare niveauPredit: string | null
  @column()
  declare quantite: number
  @column()
  declare statut: string
  @column()
  declare verdictPredit: string | null
}

export class ApproMessageSnapshotSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'enddat',
    'fournisseur',
    'id',
    'itmref',
    'mrpdat',
    'mrpmes',
    'quantity',
    'snapshotDate',
    'vcrlin',
    'vcrnum',
    'vcrseq',
  ] as const
  $columns = ApproMessageSnapshotSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare enddat: DateTime | null
  @column()
  declare fournisseur: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itmref: string
  @column.date()
  declare mrpdat: DateTime | null
  @column()
  declare mrpmes: number
  @column()
  declare quantity: number
  @column.date()
  declare snapshotDate: DateTime
  @column()
  declare vcrlin: number
  @column()
  declare vcrnum: string
  @column()
  declare vcrseq: string
}

export class CapacityClosureSchema extends BaseModel {
  static $columns = [
    'code',
    'createdAt',
    'dateFrom',
    'dateTo',
    'factor',
    'id',
    'motif',
    'scope',
  ] as const
  $columns = CapacityClosureSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dateFrom: string
  @column()
  declare dateTo: string
  @column()
  declare factor: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare motif: string
  @column()
  declare scope: string
}

export class CapacityHolidayOverrideSchema extends BaseModel {
  static $columns = ['active', 'date', 'id'] as const
  $columns = CapacityHolidayOverrideSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare date: string
  @column({ isPrimary: true })
  declare id: number
}

export class ConversationSchema extends BaseModel {
  static $columns = [
    'conversationId',
    'createdAt',
    'id',
    'messages',
    'title',
    'updatedAt',
    'userId',
  ] as const
  $columns = ConversationSchema.$columns
  @column()
  declare conversationId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare messages: string
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class DemandSnapshotSourceSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'lignes', 'snapshotDate', 'source', 'statut'] as const
  $columns = DemandSnapshotSourceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lignes: number
  @column.date()
  declare snapshotDate: DateTime
  @column()
  declare source: string
  @column()
  declare statut: string
}

export class DemandSnapshotSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'dateEcheance',
    'fournisseur',
    'id',
    'itmref',
    'itmrefori',
    'quantity',
    'snapshotDate',
    'source',
    'vcrlin',
    'vcrnum',
  ] as const
  $columns = DemandSnapshotSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare dateEcheance: DateTime | null
  @column()
  declare fournisseur: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itmref: string
  @column()
  declare itmrefori: string | null
  @column()
  declare quantity: number
  @column.date()
  declare snapshotDate: DateTime
  @column()
  declare source: string
  @column()
  declare vcrlin: string | null
  @column()
  declare vcrnum: string | null
}

export class LocalMenuSchema extends BaseModel {
  static $columns = ['chapter', 'label', 'name', 'value'] as const
  $columns = LocalMenuSchema.$columns
  @column({ isPrimary: true })
  declare chapter: number
  @column()
  declare label: string
  @column()
  declare name: string
  @column()
  declare value: number
}

export class OfOverrideSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'dateDebut',
    'dateFin',
    'id',
    'note',
    'numOf',
    'status',
    'updatedAt',
    'workstation',
  ] as const
  $columns = OfOverrideSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dateDebut: string | null
  @column()
  declare dateFin: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare note: string | null
  @column()
  declare numOf: string
  @column()
  declare status: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workstation: string | null
}

export class OrderLineOverrideSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'dateLivraison',
    'id',
    'ligne',
    'numCommande',
    'updatedAt',
  ] as const
  $columns = OrderLineOverrideSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dateLivraison: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ligne: string
  @column()
  declare numCommande: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PrintDestinationSchema extends BaseModel {
  static $columns = [
    'destCode',
    'destLabel',
    'docType',
    'id',
    'note',
    'sandbox',
    'stoloc',
    'updatedAt',
    'updatedBy',
  ] as const
  $columns = PrintDestinationSchema.$columns
  @column()
  declare destCode: string
  @column()
  declare destLabel: string
  @column()
  declare docType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare note: string
  @column()
  declare sandbox: boolean
  @column()
  declare stoloc: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string
}

export class PrintDocumentSchema extends BaseModel {
  static $columns = ['active', 'code', 'id', 'label', 'position', 'updatedAt', 'updatedBy'] as const
  $columns = PrintDocumentSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare code: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string
  @column()
  declare position: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string
}

export class PrintJobSchema extends BaseModel {
  static $columns = [
    'attempt',
    'createdAt',
    'destCode',
    'docType',
    'durationMs',
    'error',
    'id',
    'jobDetail',
    'jobPhase',
    'jobRank',
    'message',
    'ofNum',
    'origin',
    'poolEntryIdx',
    'requestedBy',
    'retCod',
    'sandbox',
    'serverVerdict',
    'status',
    'stoloc',
    'verdictInferred',
    'x3Trace',
  ] as const
  $columns = PrintJobSchema.$columns
  @column()
  declare attempt: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare destCode: string
  @column()
  declare docType: string
  @column()
  declare durationMs: number
  @column()
  declare error: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare jobDetail: string
  @column()
  declare jobPhase: string
  @column()
  declare jobRank: number
  @column()
  declare message: string
  @column()
  declare ofNum: string
  @column()
  declare origin: string
  @column()
  declare poolEntryIdx: string
  @column()
  declare requestedBy: string
  @column()
  declare retCod: string
  @column()
  declare sandbox: boolean
  @column()
  declare serverVerdict: string
  @column()
  declare status: string
  @column()
  declare stoloc: string
  @column()
  declare verdictInferred: boolean
  @column()
  declare x3Trace: string
}

export class PrintSettingSchema extends BaseModel {
  static $columns = ['autoPrintMode', 'id', 'updatedAt', 'updatedBy'] as const
  $columns = PrintSettingSchema.$columns
  @column()
  declare autoPrintMode: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string
}

export class ScenarioSchema extends BaseModel {
  static $columns = [
    'auteur',
    'createdAt',
    'dataAt',
    'description',
    'evaluatedAt',
    'id',
    'mutations',
    'nom',
    'statut',
    'strategy',
    'updatedAt',
    'userId',
  ] as const
  $columns = ScenarioSchema.$columns
  @column()
  declare auteur: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dataAt: string | null
  @column()
  declare description: string | null
  @column()
  declare evaluatedAt: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mutations: string
  @column()
  declare nom: string
  @column()
  declare statut: string
  @column()
  declare strategy: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class StaticArticleSchema extends BaseModel {
  static $columns = [
    'category',
    'code',
    'description',
    'famille',
    'reorderDelay',
    'status',
    'supplyType',
    'syncedAt',
    'typologie',
    'usParPalette',
  ] as const
  $columns = StaticArticleSchema.$columns
  @column()
  declare category: string
  @column({ isPrimary: true })
  declare code: string
  @column()
  declare description: string
  @column()
  declare famille: string
  @column()
  declare reorderDelay: number
  @column()
  declare status: number
  @column()
  declare supplyType: string
  @column()
  declare syncedAt: number
  @column()
  declare typologie: string
  @column()
  declare usParPalette: number | null
}

export class StaticGammeSchema extends BaseModel {
  static $columns = [
    'article',
    'id',
    'rate',
    'syncedAt',
    'workstation',
    'workstationLabel',
  ] as const
  $columns = StaticGammeSchema.$columns
  @column()
  declare article: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare rate: number
  @column()
  declare syncedAt: number
  @column()
  declare workstation: string
  @column()
  declare workstationLabel: string
}

export class StaticNomenclatureSchema extends BaseModel {
  static $columns = [
    'componentArticle',
    'componentDescription',
    'componentType',
    'consumptionNature',
    'id',
    'level',
    'linkQuantity',
    'parentArticle',
    'parentDescription',
    'syncedAt',
  ] as const
  $columns = StaticNomenclatureSchema.$columns
  @column()
  declare componentArticle: string
  @column()
  declare componentDescription: string
  @column()
  declare componentType: string
  @column()
  declare consumptionNature: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare level: number
  @column()
  declare linkQuantity: number
  @column()
  declare parentArticle: string
  @column()
  declare parentDescription: string
  @column()
  declare syncedAt: number
}

export class StaticWorkstationSchema extends BaseModel {
  static $columns = [
    'code',
    'daycap0',
    'daycap1',
    'daycap2',
    'daycap3',
    'daycap4',
    'daycap5',
    'daycap6',
    'description',
    'eff',
    'id',
    'shr',
    'stoloc',
    'syncedAt',
    'twd',
    'usePct',
    'wcr',
    'wcrfcy',
    'wstnbr',
    'wsttyp',
  ] as const
  $columns = StaticWorkstationSchema.$columns
  @column()
  declare code: string
  @column()
  declare daycap0: number
  @column()
  declare daycap1: number
  @column()
  declare daycap2: number
  @column()
  declare daycap3: number
  @column()
  declare daycap4: number
  @column()
  declare daycap5: number
  @column()
  declare daycap6: number
  @column()
  declare description: string
  @column()
  declare eff: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare shr: number
  @column()
  declare stoloc: string
  @column()
  declare syncedAt: number
  @column()
  declare twd: string
  @column()
  declare usePct: number
  @column()
  declare wcr: string
  @column()
  declare wcrfcy: string
  @column()
  declare wstnbr: number
  @column()
  declare wsttyp: number
}

export class StockValuationCallSchema extends BaseModel {
  static $columns = ['calledAt', 'fromDate', 'grain', 'id', 'pinned', 'toDate'] as const
  $columns = StockValuationCallSchema.$columns
  @column.dateTime()
  declare calledAt: DateTime
  @column.date()
  declare fromDate: DateTime
  @column()
  declare grain: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pinned: boolean
  @column.date()
  declare toDate: DateTime
}

export class SystemSettingSchema extends BaseModel {
  static $columns = ['key', 'updatedAt', 'updatedBy', 'value'] as const
  $columns = SystemSettingSchema.$columns
  @column({ isPrimary: true })
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string
  @column()
  declare value: string
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'dashboardLayout',
    'id',
    'lastEnv',
    'lastLoginAt',
    'updatedAt',
    'username',
    'x3PasswordEncrypted',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dashboardLayout: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastEnv: string
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare username: string
  @column()
  declare x3PasswordEncrypted: string | null
}
