import type { LucideIcon } from 'lucide-react'
import {
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  BadgeCheck,
  Ban,
  BookmarkCheck,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  CircleCheck,
  CircleCheckBig,
  CircleHelp,
  CirclePlus,
  CircleSlash,
  CircleX,
  ClipboardCheck,
  Clock,
  CloudOff,
  Download,
  Eye,
  EyeOff,
  Factory,
  FileText,
  FilterX,
  FlaskConical,
  FolderOpen,
  Gauge,
  GanttChart,
  GitBranch,
  GripVertical,
  Info,
  LayoutGrid,
  Layers,
  Lightbulb,
  List,
  ListPlus,
  LoaderCircle,
  Minus,
  Network,
  OctagonAlert,
  Package,
  Pencil,
  Play,
  Plus,
  Printer,
  Receipt,
  RefreshCw,
  Ruler,
  Save,
  Search,
  SearchX,
  Send,
  ShieldQuestion,
  ShoppingCart,
  SlidersHorizontal,
  Square,
  SquareCheckBig,
  Table,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Truck,
  Undo2,
  Wrench,
  X,
  Zap,
} from 'lucide-react'

/**
 * Correspondance Material Symbols (ligature snake_case) → composant lucide-react.
 *
 * Sert UNIQUEMENT aux icônes dont le nom arrive par la donnée (ex. `p.icon`,
 * `props.icon`) — là où on ne peut pas importer statiquement le composant lucide.
 * Les sites à icône fixe importent directement le composant lucide (tree-shaking),
 * pas ce mapping. Clés = les ligatures Material d'origine, inchangées côté data.
 */
export const MATERIAL_ICON: Record<string, LucideIcon> = {
  warning: TriangleAlert,
  close: X,
  error: CircleX,
  visibility: Eye,
  visibility_off: EyeOff,
  search: Search,
  science: FlaskConical,
  delete: Trash2,
  block: Ban,
  refresh: RefreshCw,
  local_shipping: Truck,
  inventory_2: Package,
  insights: Lightbulb,
  edit: Pencil,
  check_circle: CircleCheck,
  check: Check,
  add: Plus,
  add_circle: CirclePlus,
  tune: SlidersHorizontal,
  schedule: Clock,
  bolt: Zap,
  view_timeline: CalendarRange,
  undo: Undo2,
  trending_up: TrendingUp,
  task_alt: CircleCheckBig,
  swap_horiz: ArrowLeftRight,
  compare_arrows: ArrowLeftRight,
  straighten: Ruler,
  save: Save,
  remove: Minus,
  receipt_long: Receipt,
  queue: ListPlus,
  print: Printer,
  precision_manufacturing: Factory,
  layers: Layers,
  help_outline: CircleHelp,
  help: CircleHelp,
  gpp_maybe: ShieldQuestion,
  folder_open: FolderOpen,
  filter_alt_off: FilterX,
  filter_alt: SlidersHorizontal,
  fact_check: ClipboardCheck,
  event: CalendarDays,
  engineering: Wrench,
  drag_indicator: GripVertical,
  download: Download,
  bookmark_added: BookmarkCheck,
  arrow_upward: ArrowUp,
  arrow_forward: ArrowRight,
  arrow_downward: ArrowDown,
  arrow_back: ArrowLeft,
  account_tree: Network,
  device_hub: GitBranch,

  /* ── Valeurs dynamiques tracées (ternaires, maps, données serveur) ──
     Ajoutées à l'intégration pour que chaque nom réellement passé à
     DynamicIcon résolve vers la bonne icône (sinon fallback CircleHelp). */
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  chevron_right: ChevronRight,
  check_box: SquareCheckBig,
  check_box_outline_blank: Square,
  radio_button_unchecked: Circle,
  cloud_off: CloudOff,
  search_off: SearchX,
  report: OctagonAlert,
  info: Info,
  cancel: CircleSlash,
  inventory: Package,
  shelves: Archive,
  speed: Gauge,
  circle: Circle,
  shopping_cart: ShoppingCart,
  build_circle: Wrench,
  description: FileText,
  format_list_bulleted: List,
  play_arrow: Play,
  grid_view: LayoutGrid,
  timeline: GanttChart,
  table_rows: Table,
  bar_chart: ChartColumn,
  stacked_bar_chart: ChartColumn,
  priority_high: TriangleAlert,
  schedule_send: CalendarClock,
  verified: BadgeCheck,
  outbound: Send,
  progress_activity: LoaderCircle,
  unfold_more: ChevronsUpDown,
}

const FALLBACK: LucideIcon = CircleHelp

/**
 * Icône résolue à partir d'un nom de ligature Material (donnée runtime).
 * Tombe sur une icône d'aide discrète si le nom est inconnu — jamais de crash.
 */
export function DynamicIcon({
  name,
  size = 16,
  className,
  strokeWidth = 1.75,
}: {
  name: string | null | undefined
  size?: number
  className?: string
  strokeWidth?: number
}) {
  const Icon = (name && MATERIAL_ICON[name]) || FALLBACK
  return <Icon size={size} className={className} strokeWidth={strokeWidth} aria-hidden />
}
