/**
 * AUTO-GÉNÉRÉ par scripts/gen-routes-manifest.mjs — NE PAS ÉDITER À LA MAIN.
 * Source : `start/routes.ts` → `node ace list:routes --jsonl`.
 * Régénérer : `npm run routes:gen` · Vérifier la fraîcheur : `npm run routes:check`.
 * 45 routes nommées.
 */

export const MANIFEST = {
  "assets.css": { method: "GET", pattern: "/css/app.css" },
  "assets.js": { method: "GET", pattern: "/js/app.js" },
  "assets.unpoly_css": { method: "GET", pattern: "/vendor/unpoly.css" },
  "assets.unpoly_js": { method: "GET", pattern: "/vendor/unpoly.js" },
  "data.load": { method: "POST", pattern: "/api/v1/data/load" },
  "design_system": { method: "GET", pattern: "/design-system" },
  "health.index": { method: "GET", pattern: "/health" },
  "home": { method: "GET", pattern: "/" },
  "order_planning.board": { method: "GET", pattern: "/scheduler/planning-board" },
  "order_planning.index": { method: "GET", pattern: "/api/v1/order-planning/order-lines" },
  "order_planning.line_detail": { method: "GET", pattern: "/api/v1/order-planning/lines/:num/:ligne" },
  "order_planning.reset_override": { method: "DELETE", pattern: "/api/v1/order-planning/order-lines/:num/:ligne/override" },
  "order_planning.update": { method: "PATCH", pattern: "/api/v1/order-planning/order-lines/:num/:ligne" },
  "pipeline.suivi_status": { method: "POST", pattern: "/api/v1/pipeline/suivi-status" },
  "pipeline.supply_board": { method: "POST", pattern: "/api/v1/pipeline/supply-board" },
  "planning_board.articles_by_component": { method: "GET", pattern: "/api/v1/planning-board/articles-by-component/:component" },
  "planning_board.board_feasibility": { method: "POST", pattern: "/api/v1/planning-board/board-feasibility" },
  "planning_board.feasibility": { method: "POST", pattern: "/api/v1/planning-board/feasibility" },
  "planning_board.index": { method: "GET", pattern: "/api/v1/planning-board/ofs" },
  "planning_board.list_events": { method: "GET", pattern: "/api/v1/planning-board/events" },
  "planning_board.list_overrides": { method: "GET", pattern: "/api/v1/planning-board/overrides" },
  "planning_board.nomenclature": { method: "GET", pattern: "/api/v1/planning-board/nomenclature/:article" },
  "planning_board.of_materials": { method: "GET", pattern: "/api/v1/planning-board/of-materials/:numOf" },
  "planning_board.order_impacts": { method: "POST", pattern: "/api/v1/planning-board/order-impacts" },
  "planning_board.reload_data": { method: "POST", pattern: "/api/v1/planning-board/reload" },
  "planning_board.reset_all": { method: "DELETE", pattern: "/api/v1/planning-board/overrides" },
  "planning_board.reset_override": { method: "DELETE", pattern: "/api/v1/planning-board/ofs/:numOf/override" },
  "planning_board.search_of": { method: "GET", pattern: "/api/v1/planning-board/search/of" },
  "planning_board.search_pf": { method: "GET", pattern: "/api/v1/planning-board/search/pf" },
  "planning_board.search_poste": { method: "GET", pattern: "/api/v1/planning-board/search/poste" },
  "planning_board.shortages": { method: "GET", pattern: "/api/v1/planning-board/shortages" },
  "planning_board.show": { method: "GET", pattern: "/api/v1/planning-board/ofs/:numOf" },
  "planning_board.update": { method: "PATCH", pattern: "/api/v1/planning-board/ofs/:numOf" },
  "planning_board.whatif": { method: "POST", pattern: "/api/v1/planning-board/whatif" },
  "scheduler.expert_board": { method: "GET", pattern: "/scheduler/board" },
  "scheduler.of_detail": { method: "GET", pattern: "/scheduler/of/:num" },
  "scheduler.shortage_rows": { method: "GET", pattern: "/scheduler/shortages/rows" },
  "scheduler.shortage_tracker": { method: "GET", pattern: "/scheduler/shortages" },
  "static_sync.status": { method: "GET", pattern: "/api/v1/static/status" },
  "static_sync.sync": { method: "POST", pattern: "/api/v1/static/sync" },
  "suivi.assign": { method: "POST", pattern: "/api/v1/status/assign" },
  "suivi.from_latest_export": { method: "POST", pattern: "/api/v1/status/from-latest-export" },
  "suivi.palette": { method: "POST", pattern: "/api/v1/status/palette" },
  "suivi.retard_charge": { method: "POST", pattern: "/api/v1/status/retard-charge" },
  "suivi.status_detail": { method: "GET", pattern: "/api/v1/status/status/:noCommande" },
} as const satisfies Record<string, { method: string; pattern: string }>

export type RouteName = keyof typeof MANIFEST

/**
 * Params de path attendus par route (côté frontend).
 * `void` = aucun paramètre de path ; les query strings (?start&days…) restent à l'appelant.
 */
export type RouteParams = {
  "assets.css": void,
  "assets.js": void,
  "assets.unpoly_css": void,
  "assets.unpoly_js": void,
  "data.load": void,
  "design_system": void,
  "health.index": void,
  "home": void,
  "order_planning.board": void,
  "order_planning.index": void,
  "order_planning.line_detail": { "num": string | number; "ligne": string | number },
  "order_planning.reset_override": { "num": string | number; "ligne": string | number },
  "order_planning.update": { "num": string | number; "ligne": string | number },
  "pipeline.suivi_status": void,
  "pipeline.supply_board": void,
  "planning_board.articles_by_component": { "component": string | number },
  "planning_board.board_feasibility": void,
  "planning_board.feasibility": void,
  "planning_board.index": void,
  "planning_board.list_events": void,
  "planning_board.list_overrides": void,
  "planning_board.nomenclature": { "article": string | number },
  "planning_board.of_materials": { "numOf": string | number },
  "planning_board.order_impacts": void,
  "planning_board.reload_data": void,
  "planning_board.reset_all": void,
  "planning_board.reset_override": { "numOf": string | number },
  "planning_board.search_of": void,
  "planning_board.search_pf": void,
  "planning_board.search_poste": void,
  "planning_board.shortages": void,
  "planning_board.show": { "numOf": string | number },
  "planning_board.update": { "numOf": string | number },
  "planning_board.whatif": void,
  "scheduler.expert_board": void,
  "scheduler.of_detail": { "num": string | number },
  "scheduler.shortage_rows": void,
  "scheduler.shortage_tracker": void,
  "static_sync.status": void,
  "static_sync.sync": void,
  "suivi.assign": void,
  "suivi.from_latest_export": void,
  "suivi.palette": void,
  "suivi.retard_charge": void,
  "suivi.status_detail": { "noCommande": string | number }
}
